In [3]:
### imports
import requests
import io
import pandas as pd
import re

from bs4 import BeautifulSoup as bs

In [4]:
### config
URL = "https://www.billboard.com/charts/hot-100/"

In [6]:
### request url and let bs work
response = requests.get(URL)
soup = bs(response.text)

# cant print huge stuff in notebook w/o changing settings
#print(soup.prettify())

In [44]:
### fetch details for number 1 song as its a touch different than the rest

### NUMBER 1 font is bigger
# <span class="c-label a-font-basic u-font-size-33@desktop u-font-size-19@mobile-max u-line-height-33px">
### all other numbers same
# <span class="c-label a-font-basic u-font-size-22@desktop u-font-size-19@mobile-max u-line-height-33px">

### code for using regex 
# jobs_df.loc[x, 'Apply url'] = base_url + (re.sub(r'[^a-z0-9]+', '-', jobs_df.loc[x, 'Job Title'].lower()).rstrip('-') + '-' + str(x))



no_1_song = soup.find('span', class_='c-label a-font-basic u-font-size-33@desktop u-font-size-19@mobile-max u-line-height-33px')
no_1_song = re.search(r'\d', no_1_song.text).group()
no_1_song

'1'

In [49]:
### fetch song titles[]

song_titles = soup.find_all('h3', class_='c-title a-font-basic u-letter-spacing-0010 u-max-width-397 lrv-u-font-size-16 lrv-u-font-size-14@mobile-max u-line-height-22px u-word-spacing-0063 u-line-height-normal@mobile-max a-truncate-ellipsis-2line lrv-u-margin-b-025 lrv-u-margin-b-00@mobile-max')
song_titles = [x.text for x in song_titles]
song_titles

["\n\n\t\n\t\n\t\t\n\t\t\t\t\tChoosin' Texas\t\t\n\t\n",
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tSwim\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tMan I Need\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tI Just Might\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tOrdinary\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tSo Easy (To Fall In Love)\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tGolden\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tStateside\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tThe Fate Of Ophelia\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tFolded\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tWhere Is My Husband!\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tBe Her\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tOpalite\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tSleepless In A Hotel Room\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tRisk It All\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tBabydoll\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tIloveitiloveitiloveit\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tDracula\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tE85\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tYukon\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tFather\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tBe By You\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tAmerican Girls\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tDTMF\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tHomewrecker\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tBody\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tAll The Love\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tThe Fall\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tDie On This Hill\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tChange My Mind\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tPop Dat Thang\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tWhite Keys\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tFever Dream\t\t\n\t\n',
 "\n\n\t\n\t\n\t\t\n\t\t\t\t\tLet 'Em Know\t\t\n\t\n",
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tElizabeth Taylor\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tLush Life\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tWhat You Saying\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tThe Great Divide\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tDays Like These\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tKing\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tMotion Party\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tBody To Body\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tMidnight Sun\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tPunch Drunk\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tBrunette\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tLoving Life Again\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tMcArthur\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tPorch Light\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tWhatever Works\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tWhen Did You Get Hot?\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tThis A Must\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tRaindance\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tChanel\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tDandelion\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tRethink Some Things\t\t\n\t\n',
 "\n\n\t\n\t\n\t\t\n\t\t\t\t\tI Ain't Coming Back\t\t\n\t\n",
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tPreacher Man\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tAperture\t\t\n\t\n',
 "\n\n\t\n\t\n\t\t\n\t\t\t\t\tMama's Favorite\t\t\n\t\n",
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tIn My Room\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tBully\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tHighs And Lows\t\t\n\t\n',
 "\n\n\t\n\t\n\t\t\n\t\t\t\t\tTime's Ticking\t\t\n\t\n",
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tHooligan\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tEarrings\t\t\n\t\n',
 "\n\n\t\n\t\n\t\t\n\t\t\t\t\tWhat He'll Never Have\t\t\n\t\n",
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tSisters And Brothers\t\t\n\t\n',
 "\n\n\t\n\t\n\t\t\n\t\t\t\t\tAin't A Bad Life\t\t\n\t\n",
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tYounger You (From The "Hannah Montana 20th Anniversary Special")\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tTurn This Truck Around\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tBeautiful Things\t\t\n\t\n',
 "\n\n\t\n\t\n\t\t\n\t\t\t\t\tI Can't Wait\t\t\n\t\n",
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tNormal\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tFYA\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\t2.0\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tEnds Of The Earth\t\t\n\t\n',
 "\n\n\t\n\t\n\t\t\n\t\t\t\t\tFreakin' Out\t\t\n\t\n",
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tRein Me In\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tComing Up Roses\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tThe Visitor\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tLast Breath\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tWhite Lines\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tGo Away\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tAliens\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tBeauty And The Beast\t\t\n\t\n',
 "\n\n\t\n\t\n\t\t\n\t\t\t\t\tDon't We\t\t\n\t\n",
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tCircles\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tDry Spell\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tWhat You Need\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tLike Animals\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tZoo\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tDano\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tWho Knows\t\t\n\t\n',
 "\n\n\t\n\t\n\t\t\n\t\t\t\t\tThey Don't Know 'bout Us\t\t\n\t\n",
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tMrs. Trendsetter\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tMerry Go Round\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tGriddle\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tSilent Treatment\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tTaste Back\t\t\n\t\n',
 '\n\n\t\n\t\n\t\t\n\t\t\t\t\tPlastic Cigarette\t\t\n\t\n']

In [ ]:
<h3 id="title-of-a-story" class="c-title  a-font-basic u-letter-spacing-0010 u-max-width-397 lrv-u-font-size-16 lrv-u-font-size-14@mobile-max u-line-height-22px u-word-spacing-0063 u-line-height-normal@mobile-max a-truncate-ellipsis-2line lrv-u-margin-b-025 lrv-u-margin-b-00@mobile-max">

In [5]:
### like fetching all the images
images = soup.find_all('img')
images

[<img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>,
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>]

In [6]:
### take a look at a single image
sample_img = images[0]
sample_img

In [7]:
### pick out specfic tags within the first. can use .get() to account for tags that may not exist
print(sample_img.get('alt', "no alt"))
print(sample_img.get('src', "no src"))
print(sample_img.get('notRealTag', "no tag"))

Real Python Logo
https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1
no tag

In [8]:
### we can run through specific tags and add them to a list
### like if we want src from all images
image_src = [x.get('src') for x in images]
image_src

['https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1',
 'https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1']

# Webscraping ______________________

In [9]:
### use .find to pull first job title
### <h2 class="title is-5">Senior Python Developer</h2>
x = soup.find_all('h2')
x[0].text

'Senior Python Developer'

In [10]:
### use .find_all to get all h2 - for loop to insert .text into job_titles[]
job_titles = soup.find_all('h2')
job_titles = [x.text for x in job_titles]
job_titles

['Senior Python Developer',
 'Energy engineer',
 'Legal executive',
 'Fitness centre manager',
 'Product manager',
 'Medical technical officer',
 'Physiological scientist',
 'Textile designer',
 'Television floor manager',
 'Waste management officer',
 'Software Engineer (Python)',
 'Interpreter',
 'Architect',
 'Meteorologist',
 'Audiological scientist',
 'English as a second language teacher',
 'Surgeon',
 'Equities trader',
 'Newspaper journalist',
 'Materials engineer',
 'Python Programmer (Entry-Level)',
 'Product/process development scientist',
 'Scientist, research (maths)',
 'Ecologist',
 'Materials engineer',
 'Historic buildings inspector/conservation officer',
 'Data scientist',
 'Psychiatrist',
 'Structural engineer',
 'Immigration officer',
 'Python Programmer (Entry-Level)',
 'Neurosurgeon',
 'Broadcast engineer',
 'Make',
 'Nurse, adult',
 'Air broker',
 'Editor, film/video',
 'Production assistant, radio',
 'Engineer, communications',
 'Sales executive',
 'Software Developer (Python)',
 'Futures trader',
 'Tour manager',
 'Cytogeneticist',
 'Designer, multimedia',
 'Trade union research officer',
 'Chemist, analytical',
 'Programmer, multimedia',
 'Engineer, broadcasting (operations)',
 'Teacher, primary school',
 'Python Developer',
 'Manufacturing systems engineer',
 'Producer, television/film/video',
 'Scientist, forensic',
 'Bonds trader',
 'Editorial assistant',
 'Photographer',
 'Retail banker',
 'Jewellery designer',
 'Ophthalmologist',
 'Back-End Web Developer (Python, Django)',
 'Licensed conveyancer',
 'Futures trader',
 'Counselling psychologist',
 'Insurance underwriter',
 'Engineer, automotive',
 'Producer, radio',
 'Dispensing optician',
 'Designer, fashion/clothing',
 'Chartered loss adjuster',
 'Back-End Web Developer (Python, Django)',
 'Forest/woodland manager',
 'Clinical cytogeneticist',
 'Print production planner',
 'Systems developer',
 'Graphic designer',
 'Writer',
 'Field seismologist',
 'Chief Strategy Officer',
 'Air cabin crew',
 'Python Programmer (Entry-Level)',
 'Warden/ranger',
 'Sports therapist',
 'Arts development officer',
 'Printmaker',
 'Health and safety adviser',
 'Manufacturing systems engineer',
 'Programmer, applications',
 'Medical physicist',
 'Media planner',
 'Software Developer (Python)',
 'Surveyor, land/geomatics',
 'Legal executive',
 'Librarian, academic',
 'Barrister',
 'Museum/gallery exhibitions officer',
 'Radiographer, diagnostic',
 'Database administrator',
 'Furniture designer',
 'Ship broker']

In [11]:
### use .find_all to get all h3 - for loop to insert .text into companies[]
companies = soup.find_all('h3')
companies = [x.text for x in companies]
companies

['Payne, Roberts and Davis',
 'Vasquez-Davidson',
 'Jackson, Chambers and Levy',
 'Savage-Bradley',
 'Ramirez Inc',
 'Rogers-Yates',
 'Kramer-Klein',
 'Meyers-Johnson',
 'Hughes-Williams',
 'Jones, Williams and Villa',
 'Garcia PLC',
 'Gregory and Sons',
 'Clark, Garcia and Sosa',
 'Bush PLC',
 'Salazar-Meyers',
 'Parker, Murphy and Brooks',
 'Cruz-Brown',
 'Macdonald-Ferguson',
 'Williams, Peterson and Rojas',
 'Smith and Sons',
 'Moss, Duncan and Allen',
 'Gomez-Carroll',
 'Manning, Welch and Herring',
 'Lee, Gutierrez and Brown',
 'Davis, Serrano and Cook',
 'Smith LLC',
 'Thomas Group',
 'Silva-King',
 'Pierce-Long',
 'Walker-Simpson',
 'Cooper and Sons',
 'Donovan, Gonzalez and Figueroa',
 'Morgan, Butler and Bennett',
 'Snyder-Lee',
 'Harris PLC',
 'Washington PLC',
 'Brown, Price and Campbell',
 'Mcgee PLC',
 'Dixon Inc',
 'Thompson, Sheppard and Ward',
 'Adams-Brewer',
 'Schneider-Brady',
 'Gonzales-Frank',
 'Smith-Wong',
 'Pierce-Herrera',
 'Aguilar, Rivera and Quinn',
 'Lowe, Barnes and Thomas',
 'Lewis, Gonzalez and Vasquez',
 'Taylor PLC',
 'Oliver, Jones and Ramirez',
 'Rivera and Sons',
 'Garcia PLC',
 'Johnson, Wells and Kramer',
 'Gonzalez LLC',
 'Morgan, White and Macdonald',
 'Robinson-Fitzpatrick',
 'Waters, Wilson and Hoover',
 'Hill LLC',
 'Li-Gregory',
 'Fisher, Ryan and Coleman',
 'Stewart-Alexander',
 'Abbott and Sons',
 'Bryant, Santana and Davenport',
 'Smith PLC',
 'Patterson-Singh',
 'Martinez-Berry',
 'May, Taylor and Fisher',
 'Bailey, Owen and Thompson',
 'Vasquez Ltd',
 'Leblanc LLC',
 'Jackson, Ali and Mckee',
 'Blankenship, Knight and Powell',
 'Patton, Haynes and Jones',
 'Wood Inc',
 'Collins Group',
 'Flores-Nelson',
 'Mitchell, Jones and Olson',
 'Howard Group',
 'Kramer-Edwards',
 'Berry-Houston',
 'Mathews Inc',
 'Riley-Johnson',
 'Spencer and Sons',
 'Camacho-Sanchez',
 'Oliver and Sons',
 'Eaton PLC',
 'Stanley-Frederick',
 'Bradley LLC',
 'Parker, Goodwin and Zavala',
 'Kim-Miles',
 'Moreno-Rodriguez',
 'Brown-Ortiz',
 'Hartman PLC',
 'Brooks Inc',
 'Washington-Castillo',
 'Nguyen, Yoder and Petty',
 'Holder LLC',
 'Yates-Ferguson',
 'Ortega-Lawrence',
 'Fuentes, Walls and Castro']

In [24]:
### use .find_all('p', class_='location') to get all <p> tags with specific class tab assoc.
### make for loop to insert .text into loactions[] striping away \n and spaces
locations = soup.find_all('p', class_='location')
locations = [x.text.strip('\n').strip(' ').strip('\n') for x in locations]
locations

[]

In [13]:
### use .find_all <time> tags - for loop to insert .text into posting_date[]
posting_date = soup.find_all('time')
posting_date = [x.text for x in posting_date]
posting_date

['2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08']

In [14]:
### create DataFrame from all the scraped lists we have
jobs_df = pd.DataFrame({
    "Job Title": job_titles,
    "Company": companies,
    "Location": locations,
    "Posting Date": posting_date
})

In [15]:
### populate the apply url column using regex, strip(), and str cat to prep our url
apply_url = jobs_df['Job Title'].loc[0]
base_url = "https://realpython.github.io/fake-jobs/jobs/"

for x in range(0, len(jobs_df)):
    ### the use of .loc[] here is being removed from pandas so we have to use the next line
    #jobs_df['Job Title'].loc[x] = base_url + (re.sub(r'[^a-z0-9]+', '-', jobs_df['Job Title'].loc[x].lower()) + str(x))
    jobs_df.loc[x, 'Apply url'] = base_url + (re.sub(r'[^a-z0-9]+', '-', jobs_df.loc[x, 'Job Title'].lower()).rstrip('-') + '-' + str(x))
    
    print(jobs_df['Apply url'].loc[x])

https://realpython.github.io/fake-jobs/jobs/senior-python-developer-0
https://realpython.github.io/fake-jobs/jobs/energy-engineer-1
https://realpython.github.io/fake-jobs/jobs/legal-executive-2
https://realpython.github.io/fake-jobs/jobs/fitness-centre-manager-3
https://realpython.github.io/fake-jobs/jobs/product-manager-4
https://realpython.github.io/fake-jobs/jobs/medical-technical-officer-5
https://realpython.github.io/fake-jobs/jobs/physiological-scientist-6
https://realpython.github.io/fake-jobs/jobs/textile-designer-7
https://realpython.github.io/fake-jobs/jobs/television-floor-manager-8
https://realpython.github.io/fake-jobs/jobs/waste-management-officer-9
https://realpython.github.io/fake-jobs/jobs/software-engineer-python-10
https://realpython.github.io/fake-jobs/jobs/interpreter-11
https://realpython.github.io/fake-jobs/jobs/architect-12
https://realpython.github.io/fake-jobs/jobs/meteorologist-13
https://realpython.github.io/fake-jobs/jobs/audiological-scientist-14
https://realpython.github.io/fake-jobs/jobs/english-as-a-second-language-teacher-15
https://realpython.github.io/fake-jobs/jobs/surgeon-16
https://realpython.github.io/fake-jobs/jobs/equities-trader-17
https://realpython.github.io/fake-jobs/jobs/newspaper-journalist-18
https://realpython.github.io/fake-jobs/jobs/materials-engineer-19
https://realpython.github.io/fake-jobs/jobs/python-programmer-entry-level-20
https://realpython.github.io/fake-jobs/jobs/product-process-development-scientist-21
https://realpython.github.io/fake-jobs/jobs/scientist-research-maths-22
https://realpython.github.io/fake-jobs/jobs/ecologist-23
https://realpython.github.io/fake-jobs/jobs/materials-engineer-24
https://realpython.github.io/fake-jobs/jobs/historic-buildings-inspector-conservation-officer-25
https://realpython.github.io/fake-jobs/jobs/data-scientist-26
https://realpython.github.io/fake-jobs/jobs/psychiatrist-27
https://realpython.github.io/fake-jobs/jobs/structural-engineer-28
https://realpython.github.io/fake-jobs/jobs/immigration-officer-29
https://realpython.github.io/fake-jobs/jobs/python-programmer-entry-level-30
https://realpython.github.io/fake-jobs/jobs/neurosurgeon-31
https://realpython.github.io/fake-jobs/jobs/broadcast-engineer-32
https://realpython.github.io/fake-jobs/jobs/make-33
https://realpython.github.io/fake-jobs/jobs/nurse-adult-34
https://realpython.github.io/fake-jobs/jobs/air-broker-35
https://realpython.github.io/fake-jobs/jobs/editor-film-video-36
https://realpython.github.io/fake-jobs/jobs/production-assistant-radio-37
https://realpython.github.io/fake-jobs/jobs/engineer-communications-38
https://realpython.github.io/fake-jobs/jobs/sales-executive-39
https://realpython.github.io/fake-jobs/jobs/software-developer-python-40
https://realpython.github.io/fake-jobs/jobs/futures-trader-41
https://realpython.github.io/fake-jobs/jobs/tour-manager-42
https://realpython.github.io/fake-jobs/jobs/cytogeneticist-43
https://realpython.github.io/fake-jobs/jobs/designer-multimedia-44
https://realpython.github.io/fake-jobs/jobs/trade-union-research-officer-45
https://realpython.github.io/fake-jobs/jobs/chemist-analytical-46
https://realpython.github.io/fake-jobs/jobs/programmer-multimedia-47
https://realpython.github.io/fake-jobs/jobs/engineer-broadcasting-operations-48
https://realpython.github.io/fake-jobs/jobs/teacher-primary-school-49
https://realpython.github.io/fake-jobs/jobs/python-developer-50
https://realpython.github.io/fake-jobs/jobs/manufacturing-systems-engineer-51
https://realpython.github.io/fake-jobs/jobs/producer-television-film-video-52
https://realpython.github.io/fake-jobs/jobs/scientist-forensic-53
https://realpython.github.io/fake-jobs/jobs/bonds-trader-54
https://realpython.github.io/fake-jobs/jobs/editorial-assistant-55
https://realpython.github.io/fake-jobs/jobs/photographer-56
https://realpython.github.io/fake-jobs/jobs/retail-banker-57
https://realpython.github.io/fake-jobs/jobs/jewellery-designer-58
https://realpython.github.io/fake-jobs/jobs/ophthalmologist-59
https://realpython.github.io/fake-jobs/jobs/back-end-web-developer-python-django-60
https://realpython.github.io/fake-jobs/jobs/licensed-conveyancer-61
https://realpython.github.io/fake-jobs/jobs/futures-trader-62
https://realpython.github.io/fake-jobs/jobs/counselling-psychologist-63
https://realpython.github.io/fake-jobs/jobs/insurance-underwriter-64
https://realpython.github.io/fake-jobs/jobs/engineer-automotive-65
https://realpython.github.io/fake-jobs/jobs/producer-radio-66
https://realpython.github.io/fake-jobs/jobs/dispensing-optician-67
https://realpython.github.io/fake-jobs/jobs/designer-fashion-clothing-68
https://realpython.github.io/fake-jobs/jobs/chartered-loss-adjuster-69
https://realpython.github.io/fake-jobs/jobs/back-end-web-developer-python-django-70
https://realpython.github.io/fake-jobs/jobs/forest-woodland-manager-71
https://realpython.github.io/fake-jobs/jobs/clinical-cytogeneticist-72
https://realpython.github.io/fake-jobs/jobs/print-production-planner-73
https://realpython.github.io/fake-jobs/jobs/systems-developer-74
https://realpython.github.io/fake-jobs/jobs/graphic-designer-75
https://realpython.github.io/fake-jobs/jobs/writer-76
https://realpython.github.io/fake-jobs/jobs/field-seismologist-77
https://realpython.github.io/fake-jobs/jobs/chief-strategy-officer-78
https://realpython.github.io/fake-jobs/jobs/air-cabin-crew-79
https://realpython.github.io/fake-jobs/jobs/python-programmer-entry-level-80
https://realpython.github.io/fake-jobs/jobs/warden-ranger-81
https://realpython.github.io/fake-jobs/jobs/sports-therapist-82
https://realpython.github.io/fake-jobs/jobs/arts-development-officer-83
https://realpython.github.io/fake-jobs/jobs/printmaker-84
https://realpython.github.io/fake-jobs/jobs/health-and-safety-adviser-85
https://realpython.github.io/fake-jobs/jobs/manufacturing-systems-engineer-86
https://realpython.github.io/fake-jobs/jobs/programmer-applications-87
https://realpython.github.io/fake-jobs/jobs/medical-physicist-88
https://realpython.github.io/fake-jobs/jobs/media-planner-89
https://realpython.github.io/fake-jobs/jobs/software-developer-python-90
https://realpython.github.io/fake-jobs/jobs/surveyor-land-geomatics-91
https://realpython.github.io/fake-jobs/jobs/legal-executive-92
https://realpython.github.io/fake-jobs/jobs/librarian-academic-93
https://realpython.github.io/fake-jobs/jobs/barrister-94
https://realpython.github.io/fake-jobs/jobs/museum-gallery-exhibitions-officer-95
https://realpython.github.io/fake-jobs/jobs/radiographer-diagnostic-96
https://realpython.github.io/fake-jobs/jobs/database-administrator-97
https://realpython.github.io/fake-jobs/jobs/furniture-designer-98
https://realpython.github.io/fake-jobs/jobs/ship-broker-99

In [16]:
### define function to return job desc from related webpage and use .apply()
def get_desc(url):
    response = requests.get(url)
    soup = bs(response.text)
    content = soup.find_all('p')
    return content[1].text.strip()

jobs_df['Job Desc'] = jobs_df['Apply url'].apply(get_desc)
jobs_df

,Job Title,Company,Location,Posting Date,Apply url,Job Desc
0,Senior Python Developer,"Payne, Roberts and Davis","Stewartbury, AA",2021-04-08,https://realpython.github.io/fake-jobs/jobs/se...,Professional asset web application environment...
1,Energy engineer,Vasquez-Davidson,"Christopherville, AA",2021-04-08,https://realpython.github.io/fake-jobs/jobs/en...,Party prevent live. Quickly candidate change a...
2,Legal executive,"Jackson, Chambers and Levy","Port Ericaburgh, AA",2021-04-08,https://realpython.github.io/fake-jobs/jobs/le...,Administration even relate head color. Staff b...
3,Fitness centre manager,Savage-Bradley,"East Seanview, AP",2021-04-08,https://realpython.github.io/fake-jobs/jobs/fi...,Tv program actually race tonight themselves tr...
4,Product manager,Ramirez Inc,"North Jamieview, AP",2021-04-08,https://realpython.github.io/fake-jobs/jobs/pr...,Traditional page a although for study anyone. ...
...,...,...,...,...,...,...
95,Museum/gallery exhibitions officer,"Nguyen, Yoder and Petty","Lake Abigail, AE",2021-04-08,https://realpython.github.io/fake-jobs/jobs/mu...,Paper age physical current note. There reality...
96,"Radiographer, diagnostic",Holder LLC,"Jacobshire, AP",2021-04-08,https://realpython.github.io/fake-jobs/jobs/ra...,Able such right culture. Wrong pick structure ...
97,Database administrator,Yates-Ferguson,"Port Susan, AE",2021-04-08,https://realpython.github.io/fake-jobs/jobs/da...,Create day party decade high clear. Past trade...
98,Furniture designer,Ortega-Lawrence,"North Tiffany, AA",2021-04-08,https://realpython.github.io/fake-jobs/jobs/fu...,Pressure under rock next week. Recognize so re...
99,Ship broker,"Fuentes, Walls and Castro","Michelleville, AP",2021-04-08,https://realpython.github.io/fake-jobs/jobs/sh...,Management common popular project only. Must s...

In [17]:
### this version still uses the above function but inserts the desc row by row with for loop
for x in range(0, len(jobs_df)):
    #jobs_df['Job Title'].loc[x] = base_url + (re.sub(r'[^a-z0-9]+', '-', jobs_df['Job Title'].loc[x].lower()) + str(x))
    jobs_df.loc[x, 'Job Desc'] = get_desc(jobs_df.loc[x, 'Apply url'])

jobs_df

,Job Title,Company,Location,Posting Date,Apply url,Job Desc
0,Senior Python Developer,"Payne, Roberts and Davis","Stewartbury, AA",2021-04-08,https://realpython.github.io/fake-jobs/jobs/se...,Professional asset web application environment...
1,Energy engineer,Vasquez-Davidson,"Christopherville, AA",2021-04-08,https://realpython.github.io/fake-jobs/jobs/en...,Party prevent live. Quickly candidate change a...
2,Legal executive,"Jackson, Chambers and Levy","Port Ericaburgh, AA",2021-04-08,https://realpython.github.io/fake-jobs/jobs/le...,Administration even relate head color. Staff b...
3,Fitness centre manager,Savage-Bradley,"East Seanview, AP",2021-04-08,https://realpython.github.io/fake-jobs/jobs/fi...,Tv program actually race tonight themselves tr...
4,Product manager,Ramirez Inc,"North Jamieview, AP",2021-04-08,https://realpython.github.io/fake-jobs/jobs/pr...,Traditional page a although for study anyone. ...
...,...,...,...,...,...,...
95,Museum/gallery exhibitions officer,"Nguyen, Yoder and Petty","Lake Abigail, AE",2021-04-08,https://realpython.github.io/fake-jobs/jobs/mu...,Paper age physical current note. There reality...
96,"Radiographer, diagnostic",Holder LLC,"Jacobshire, AP",2021-04-08,https://realpython.github.io/fake-jobs/jobs/ra...,Able such right culture. Wrong pick structure ...
97,Database administrator,Yates-Ferguson,"Port Susan, AE",2021-04-08,https://realpython.github.io/fake-jobs/jobs/da...,Create day party decade high clear. Past trade...
98,Furniture designer,Ortega-Lawrence,"North Tiffany, AA",2021-04-08,https://realpython.github.io/fake-jobs/jobs/fu...,Pressure under rock next week. Recognize so re...
99,Ship broker,"Fuentes, Walls and Castro","Michelleville, AP",2021-04-08,https://realpython.github.io/fake-jobs/jobs/sh...,Management common popular project only. Must s...